baseURL = "https://itunesrichpresence.bootleg.technology"
languageCode = "en-us"
title = "iTunesRichPresence"

theme = "vex-hugo"

[params]
  description = ""

  # Put your custom stylesheets and scripts
  custom_stylesheets = []
  custom_scripts = ["scripts/redirect.js"]

  # Additional meta
  [[params.meta]]
    name = ""
    description = ""

  # Navigation bar informations
  [params.navbar]
    logo = "iTunesRichPresence"
    [[params.navbar.menu]]
      link = "#"
      text = "HOME"
    [[params.navbar.menu]]
      link = "https://github.com/nint8835/iTunesRichPresence"
      text = "GITHUB"
    [[params.navbar.menu]]
      link = "https://discord.gg/57a8dqb"
      text = "DISCORD"
    [[params.navbar.menu]]
      link = "https://ko-fi.com/O5O2FSWT"
      text = "DONATE"

  # Header
  [params.header]
    title = "Bring your iTunes now playing information to Discord"
    text = "iTunesRichPresence easily and quickly integrates iTunes with Discord via Rich Presence, allowing you to show off what you are listening to at any moment in time."
    [params.header.image]
      path = "images/discord_popout.png"
      alt = "Watch"
    [params.header.button]
      link = "https://github.com/nint8835/iTunesRichPresence/releases"
      text = "Download Now"

  # Features
  [params.features]
    title = "Our Core Features"
    [params.features.image]
      path = "images/client.png"
      alt = "Watch"
    # Menu at the left of the image
    [[params.features.left]]
      icon = "tf-ion-ios-compose-outline"
      title = "Customizable Design"
      text = "Easily customize the way the status appears in different states using a simple-to-use token system."
    [[params.features.left]]
      icon = "tf-ion-ios-bolt-outline"
      title = "Lightweight"
      text = "Weighing in at a filesize of 8MB and an average memory usage of 30MB, this app has almost no fingerprint on your system."
